name: Mule Action
description: Action to test and deploy Mule Apps

inputs:
  testParams:
    description: Parameters for Maven test goal (must include all -D directives)
    required: true
  deployParams:
    description: Parameters for Maven deploy goal (must include all -D directives)
    required: true
  deployToExchange:
    description: Deploy to Exchange? (boolean)
    required: true
  projectName:
    description: Name of the final JAR file (without jar extension)
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Download settings.xml
      uses: actions/download-artifact@v2
      with:
        name: settings
    - shell: bash
      run: |
        cat settings.xml
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
      shell: bash
    
    # test, package y deploy a exchange
    
    - name: Test with Maven. Assumes coverage values configured in pom.xml
      run: mvn clean test -e -s settings.xml ${{ inputs.testParams }}
      shell: bash
      
    - name: Check if deployToExchange is true, then deploy to Exchange
      run: |
        if [[ "${{ inputs.deployToExchange }}" = true ]]; then
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}
          git add pom.xml
          git commit -m "Updating pom.xml version for Exchange"
          git push origin master
          mvn clean deploy -e -s settings.xml -DskipTests -Dmule.artifact=target/checkout/target/${{ inputs.projectName }}-${{ inputs.releaseVersion }}-jar-with-dependencies.jar;
        fi
      shell: bash
      
    - name: Deploy to CloudHub
      run: mvn clean deploy -e -s settings.xml -DskipTests -DmuleDeploy ${{ inputs.deployParams }}
      shell: bash
