name: Update version
description: Action update Mule App version
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Download settings.xml
      uses: actions/download-artifact@v2
      with:
        name: settings
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
      shell: bash
      
    - name: Update version
      run: |
          mvn build-helper:parse-version -s settings.xml versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}
          git add pom.xml
          git commit -m "Updating pom.xml version for Exchange"
          git push origin master
      shell: bash
