name: Deploy to Cloudhub
description: Action to deploy Mule Apps

inputs:
  deployParams:
    description: Parameters for Maven deploy goal (must include all -D directives)
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Download settings.xml
      uses: actions/download-artifact@v2
      with:
        name: settings
        
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Deploy to CloudHub if versionUpdated = false
      run: |
        mvn clean deploy -e -s settings.xml -DskipTests -DmuleDeploy ${{ inputs.deployParams }}
      shell: bash
