name: Test Mule App
description: Action to test Mule Apps with Maven

inputs:
  testParams:
    description: Parameters for Maven test goal (must include all -D directives)
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    
    - name: Download settings.xml
      uses: actions/download-artifact@v2
      with:
        name: settings
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Test with Maven.
      run: mvn clean test -e -s settings.xml ${{ inputs.testParams }}
      shell: bash
